### ISSUE TITLE
Cannot use Wallet through extension

### ISSUE THREAD

**Issue by PauloLimaHQ** [Stuyk/ultra-cpp-extension#11]
I am encountering an issue while using the Wallet commands macOS. 

Specifically, I am unable to create a wallet successfully. Whenever I attempt to delete the wallet using the command "Ultra: Wallet - Destroy," I receive info stating "Wallet was deleted!" even though I have tried to create it after that, then received the `Wallet already exists!`.

I cannot do any further commands, I don't know the "existing"  wallet password, and it isn't my default wallet previously installed in my machine for instance...

**Additional Information:**

_Operating System:_ macOS (ventura 13.4.1 (22F82))
_Ultra Smart Contract Toolkit version:_ v1.3.8

Please let me know if you require further information or if there is anything else I can assist you with.

**Comment by Stuyk** [comment]
Resolved in `1.3.9`

**Comment by PauloLimaHQ** [comment]
Worked as a charm on the latest version, thanks @Stuyk!
